// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type AddInventoryCopyInput struct {
	Isbn    string `json:"isbn"`
	Barcode string `json:"barcode"`
}

type CatalogTitle struct {
	Isbn       string    `json:"isbn"`
	DtCreated  time.Time `json:"dtCreated"`
	DtModified time.Time `json:"dtModified"`
	Title      string    `json:"title"`
	AuthorName string    `json:"authorName"`
}

type CreateCatalogTitleInput struct {
	Isbn       string `json:"isbn"`
	Title      string `json:"title"`
	AuthorName string `json:"authorName"`
}

type InventoryCopy struct {
	Barcode    string              `json:"barcode"`
	DtCreated  time.Time           `json:"dtCreated"`
	DtModified time.Time           `json:"dtModified"`
	Status     InventoryCopyStatus `json:"status"`
}

type LibraryMember struct {
	MemberNumber   string              `json:"memberNumber"`
	DtCreated      time.Time           `json:"dtCreated"`
	DtModified     time.Time           `json:"dtModified"`
	Status         LibraryMemberStatus `json:"status"`
	FullName       string              `json:"fullName"`
	MaxActiveLoans int                 `json:"maxActiveLoans"`
}

type LoanRecord struct {
	LoanNumber string     `json:"loanNumber"`
	DtCreated  time.Time  `json:"dtCreated"`
	DtModified time.Time  `json:"dtModified"`
	DueAt      *time.Time `json:"dueAt,omitempty"`
	ReturnedAt *time.Time `json:"returnedAt,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type RegisterMemberInput struct {
	FullName       string `json:"fullName"`
	MaxActiveLoans int    `json:"maxActiveLoans"`
}

type StartLoanInput struct {
	MemberNumber string `json:"memberNumber"`
	Barcode      string `json:"barcode"`
}

type InventoryCopyStatus string

const (
	InventoryCopyStatusActive      InventoryCopyStatus = "ACTIVE"
	InventoryCopyStatusMaintenance InventoryCopyStatus = "MAINTENANCE"
	InventoryCopyStatusLost        InventoryCopyStatus = "LOST"
)

var AllInventoryCopyStatus = []InventoryCopyStatus{
	InventoryCopyStatusActive,
	InventoryCopyStatusMaintenance,
	InventoryCopyStatusLost,
}

func (e InventoryCopyStatus) IsValid() bool {
	switch e {
	case InventoryCopyStatusActive, InventoryCopyStatusMaintenance, InventoryCopyStatusLost:
		return true
	}
	return false
}

func (e InventoryCopyStatus) String() string {
	return string(e)
}

func (e *InventoryCopyStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = InventoryCopyStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid InventoryCopyStatus", str)
	}
	return nil
}

func (e InventoryCopyStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *InventoryCopyStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e InventoryCopyStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type LibraryMemberStatus string

const (
	LibraryMemberStatusActive    LibraryMemberStatus = "ACTIVE"
	LibraryMemberStatusSuspended LibraryMemberStatus = "SUSPENDED"
)

var AllLibraryMemberStatus = []LibraryMemberStatus{
	LibraryMemberStatusActive,
	LibraryMemberStatusSuspended,
}

func (e LibraryMemberStatus) IsValid() bool {
	switch e {
	case LibraryMemberStatusActive, LibraryMemberStatusSuspended:
		return true
	}
	return false
}

func (e LibraryMemberStatus) String() string {
	return string(e)
}

func (e *LibraryMemberStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = LibraryMemberStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid LibraryMemberStatus", str)
	}
	return nil
}

func (e LibraryMemberStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *LibraryMemberStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e LibraryMemberStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
