package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"

	"github.com/christophercaldwell/model-architecture/go/internal/application/commands"
	"github.com/christophercaldwell/model-architecture/go/internal/domain/book"
	"github.com/christophercaldwell/model-architecture/go/internal/domain/bookcopy"
	"github.com/christophercaldwell/model-architecture/go/internal/domain/loan"
	"github.com/christophercaldwell/model-architecture/go/internal/domain/member"
	"github.com/christophercaldwell/model-architecture/go/internal/transport/graphql/generated"
	"github.com/christophercaldwell/model-architecture/go/internal/transport/graphql/model"
)

func bookToModel(b *book.Book) *model.CatalogTitle {
	return &model.CatalogTitle{
		Isbn:       b.ISBN,
		DtCreated:  b.DtCreated,
		DtModified: b.DtModified,
		Title:      b.Title,
		AuthorName: b.AuthorName,
	}
}

func bookCopyToModel(bc *bookcopy.BookCopy) *model.InventoryCopy {
	return &model.InventoryCopy{
		Barcode:    bc.Barcode,
		DtCreated:  bc.DtCreated,
		DtModified: bc.DtModified,
		Status:     bookCopyStatusToModel(bc.Status),
	}
}

func bookCopyStatusToModel(s bookcopy.BookCopyStatus) model.InventoryCopyStatus {
	switch s {
	case bookcopy.BookCopyStatusMaintenance:
		return model.InventoryCopyStatusMaintenance
	case bookcopy.BookCopyStatusLost:
		return model.InventoryCopyStatusLost
	default:
		return model.InventoryCopyStatusActive
	}
}

func memberToModel(m *member.Member) *model.LibraryMember {
	return &model.LibraryMember{
		MemberNumber:   string(m.Ident),
		DtCreated:      m.DtCreated,
		DtModified:     m.DtModified,
		Status:         memberStatusToModel(m.Status),
		FullName:       m.FullName,
		MaxActiveLoans: int(m.MaxActiveLoans),
	}
}

func memberStatusToModel(s member.MemberStatus) model.LibraryMemberStatus {
	if s == member.MemberStatusSuspended {
		return model.LibraryMemberStatusSuspended
	}
	return model.LibraryMemberStatusActive
}

func loanToModel(l *loan.Loan) *model.LoanRecord {
	return &model.LoanRecord{
		LoanNumber: string(l.Ident),
		DtCreated:  l.DtCreated,
		DtModified: l.DtModified,
		DueAt:      l.DtDue,
		ReturnedAt: l.DtReturned,
	}
}

// CreateBook is the resolver for the createBook field.
func (r *mutationResolver) CreateBook(ctx context.Context, input model.CreateCatalogTitleInput) (*model.CatalogTitle, error) {
	b, err := r.Resolver.deps.Catalog.Commands.AddBook(ctx, book.BookCreationPayload{
		ISBN:       input.Isbn,
		Title:      input.Title,
		AuthorName: input.AuthorName,
	})
	if err != nil {
		return nil, fmt.Errorf("create book: %w", err)
	}
	return bookToModel(b), nil
}

// AddBookCopy is the resolver for the addBookCopy field.
func (r *mutationResolver) AddBookCopy(ctx context.Context, input model.AddInventoryCopyInput) (*model.InventoryCopy, error) {
	bc, err := r.Resolver.deps.Catalog.Commands.AddBookCopy(ctx, commands.AddBookCopyInput{
		ISBN:    input.Isbn,
		Barcode: input.Barcode,
	})
	if err != nil {
		return nil, fmt.Errorf("add book copy: %w", err)
	}
	return bookCopyToModel(bc), nil
}

// MarkBookCopyLost is the resolver for the markBookCopyLost field.
func (r *mutationResolver) MarkBookCopyLost(ctx context.Context, barcode string) (*model.InventoryCopy, error) {
	bc, err := r.Resolver.deps.Catalog.Commands.MarkBookCopyLost(ctx, barcode)
	if err != nil {
		return nil, fmt.Errorf("mark book copy lost: %w", err)
	}
	return bookCopyToModel(bc), nil
}

// MarkBookCopyFound is the resolver for the markBookCopyFound field.
func (r *mutationResolver) MarkBookCopyFound(ctx context.Context, barcode string) (*model.InventoryCopy, error) {
	bc, err := r.Resolver.deps.Catalog.Commands.MarkBookCopyFound(ctx, barcode)
	if err != nil {
		return nil, fmt.Errorf("mark book copy found: %w", err)
	}
	return bookCopyToModel(bc), nil
}

// SendBookCopyToMaintenance is the resolver for the sendBookCopyToMaintenance field.
func (r *mutationResolver) SendBookCopyToMaintenance(ctx context.Context, barcode string) (*model.InventoryCopy, error) {
	bc, err := r.Resolver.deps.Catalog.Commands.SendBookCopyToMaintenance(ctx, barcode)
	if err != nil {
		return nil, fmt.Errorf("send book copy to maintenance: %w", err)
	}
	return bookCopyToModel(bc), nil
}

// CompleteBookCopyMaintenance is the resolver for the completeBookCopyMaintenance field.
func (r *mutationResolver) CompleteBookCopyMaintenance(ctx context.Context, barcode string) (*model.InventoryCopy, error) {
	bc, err := r.Resolver.deps.Catalog.Commands.CompleteBookCopyMaintenance(ctx, barcode)
	if err != nil {
		return nil, fmt.Errorf("complete book copy maintenance: %w", err)
	}
	return bookCopyToModel(bc), nil
}

// RegisterMember is the resolver for the registerMember field.
func (r *mutationResolver) RegisterMember(ctx context.Context, input model.RegisterMemberInput) (*model.LibraryMember, error) {
	m, err := r.Resolver.deps.Membership.Commands.RegisterMember(ctx, member.MemberCreationPayload{
		FullName:       input.FullName,
		MaxActiveLoans: int16(input.MaxActiveLoans),
	})
	if err != nil {
		return nil, fmt.Errorf("register member: %w", err)
	}
	return memberToModel(m), nil
}

// SuspendMember is the resolver for the suspendMember field.
func (r *mutationResolver) SuspendMember(ctx context.Context, memberNumber string) (*model.LibraryMember, error) {
	m, err := r.Resolver.deps.Membership.Commands.SuspendMember(ctx, commands.MemberIdentInput{MemberIdent: memberNumber})
	if err != nil {
		return nil, fmt.Errorf("suspend member: %w", err)
	}
	return memberToModel(m), nil
}

// ReactivateMember is the resolver for the reactivateMember field.
func (r *mutationResolver) ReactivateMember(ctx context.Context, memberNumber string) (*model.LibraryMember, error) {
	m, err := r.Resolver.deps.Membership.Commands.ReactivateMember(ctx, commands.MemberIdentInput{MemberIdent: memberNumber})
	if err != nil {
		return nil, fmt.Errorf("reactivate member: %w", err)
	}
	return memberToModel(m), nil
}

// CheckOutBookCopy is the resolver for the checkOutBookCopy field.
func (r *mutationResolver) CheckOutBookCopy(ctx context.Context, input model.StartLoanInput) (*model.LoanRecord, error) {
	l, err := r.Resolver.deps.Lending.Commands.CheckOutBookCopy(ctx, commands.CheckOutBookCopyInput{
		MemberIdent:     input.MemberNumber,
		BookCopyBarcode: input.Barcode,
	})
	if err != nil {
		return nil, fmt.Errorf("check out book copy: %w", err)
	}
	return loanToModel(l), nil
}

// ReturnBookCopy is the resolver for the returnBookCopy field.
func (r *mutationResolver) ReturnBookCopy(ctx context.Context, barcode string) (*model.LoanRecord, error) {
	l, err := r.Resolver.deps.Lending.Commands.ReturnBookCopy(ctx, barcode)
	if err != nil {
		return nil, fmt.Errorf("return book copy: %w", err)
	}
	return loanToModel(l), nil
}

// ReportLostLoanedBookCopy is the resolver for the reportLostLoanedBookCopy field.
func (r *mutationResolver) ReportLostLoanedBookCopy(ctx context.Context, barcode string) (*model.InventoryCopy, error) {
	bc, err := r.Resolver.deps.Lending.Commands.ReportLostLoanedBookCopy(ctx, barcode)
	if err != nil {
		return nil, fmt.Errorf("report lost loaned book copy: %w", err)
	}
	return bookCopyToModel(bc), nil
}

// Books is the resolver for the books field.
func (r *queryResolver) Books(ctx context.Context) ([]*model.CatalogTitle, error) {
	books, err := r.Resolver.deps.Catalog.Queries.GetBookCatalog(ctx)
	if err != nil {
		return nil, fmt.Errorf("get books: %w", err)
	}
	result := make([]*model.CatalogTitle, len(books))
	for i := range books {
		result[i] = bookToModel(&books[i])
	}
	return result, nil
}

// BookByIsbn is the resolver for the bookByIsbn field.
func (r *queryResolver) BookByIsbn(ctx context.Context, isbn string) (*model.CatalogTitle, error) {
	b, err := r.Resolver.deps.Catalog.Queries.GetBookByISBN(ctx, isbn)
	if err != nil {
		return nil, fmt.Errorf("get book by isbn: %w", err)
	}
	if b == nil {
		return nil, nil
	}
	return bookToModel(b), nil
}

// BookCopy is the resolver for the bookCopy field.
func (r *queryResolver) BookCopy(ctx context.Context, barcode string) (*model.InventoryCopy, error) {
	bc, err := r.Resolver.deps.Catalog.Queries.GetBookCopyDetails(ctx, barcode)
	if err != nil {
		return nil, fmt.Errorf("get book copy: %w", err)
	}
	if bc == nil {
		return nil, nil
	}
	return bookCopyToModel(bc), nil
}

// Member is the resolver for the member field.
func (r *queryResolver) Member(ctx context.Context, memberNumber string) (*model.LibraryMember, error) {
	m, err := r.Resolver.deps.Membership.Queries.GetMemberDetails(ctx, member.MemberIdent(memberNumber))
	if err != nil {
		return nil, fmt.Errorf("get member: %w", err)
	}
	if m == nil {
		return nil, nil
	}
	return memberToModel(m), nil
}

// MemberLoans is the resolver for the memberLoans field.
func (r *queryResolver) MemberLoans(ctx context.Context, memberNumber string) ([]*model.LoanRecord, error) {
	loans, err := r.Resolver.deps.Lending.Queries.GetMemberLoans(ctx, member.MemberIdent(memberNumber))
	if err != nil {
		return nil, fmt.Errorf("get member loans: %w", err)
	}
	result := make([]*model.LoanRecord, len(loans))
	for i := range loans {
		result[i] = loanToModel(&loans[i])
	}
	return result, nil
}

// OverdueLoans is the resolver for the overdueLoans field.
func (r *queryResolver) OverdueLoans(ctx context.Context) ([]*model.LoanRecord, error) {
	loans, err := r.Resolver.deps.Lending.Queries.GetOverdueLoans(ctx)
	if err != nil {
		return nil, fmt.Errorf("get overdue loans: %w", err)
	}
	result := make([]*model.LoanRecord, len(loans))
	for i := range loans {
		result[i] = loanToModel(&loans[i])
	}
	return result, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
